const ACTION_TYPE = {
  ADD_TITLE: "ADD_TITLE",
  ADD_DESCRIPTION: "ADD_DESCRIPTION",
  ADD_TAG: "ADD_TAG",
  ADD_TIME: "ADD_TIME",
  SUMBIT_TASK: "SUMBIT_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  EDIT_TASK: "EDIT_TASK",
};
export { ACTION_TYPE };
